version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
      - ./scraped_results:/app/scraped_results
      - ./illustrations:/app/illustrations
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped 